import { Company } from "./types/company.types";

export const mockCompanies: Company[] = [
  {
    id: 1,
    name: "TechVision Inc.",
    location: "San Francisco, CA",
    industry: "Technology",
    employees: 1250,
    founded: 2010,
    revenue: "$125M",
    description: "Leading AI and machine learning solutions provider",
  },
  {
    id: 2,
    name: "GlobalTrade Solutions",
    location: "New York, NY",
    industry: "Finance",
    employees: 3400,
    founded: 2005,
    revenue: "$450M",
    description: "International trading platform and financial services",
  },
  {
    id: 3,
    name: "HealthFirst Medical",
    location: "Boston, MA",
    industry: "Healthcare",
    employees: 890,
    founded: 2015,
    revenue: "$78M",
    description: "Digital healthcare and telemedicine solutions",
  },
  {
    id: 4,
    name: "EcoEnergy Corp",
    location: "Austin, TX",
    industry: "Energy",
    employees: 2100,
    founded: 2012,
    revenue: "$340M",
    description: "Renewable energy and sustainable power solutions",
  },
  {
    id: 5,
    name: "DataStream Analytics",
    location: "Seattle, WA",
    industry: "Technology",
    employees: 670,
    founded: 2018,
    revenue: "$95M",
    description: "Big data analytics and business intelligence",
  },
  {
    id: 6,
    name: "RetailPro Networks",
    location: "Chicago, IL",
    industry: "Retail",
    employees: 5600,
    founded: 2008,
    revenue: "$890M",
    description: "E-commerce and retail management platform",
  },
  {
    id: 7,
    name: "AutoDrive Systems",
    location: "Detroit, MI",
    industry: "Automotive",
    employees: 1800,
    founded: 2016,
    revenue: "$210M",
    description: "Autonomous vehicle technology and systems",
  },
  {
    id: 8,
    name: "CloudNine Services",
    location: "San Jose, CA",
    industry: "Technology",
    employees: 920,
    founded: 2014,
    revenue: "$145M",
    description: "Cloud infrastructure and managed services",
  },
  {
    id: 9,
    name: "BioMed Innovations",
    location: "San Diego, CA",
    industry: "Healthcare",
    employees: 1450,
    founded: 2011,
    revenue: "$198M",
    description: "Biotechnology and pharmaceutical research",
  },
  {
    id: 10,
    name: "FinanceHub Group",
    location: "Charlotte, NC",
    industry: "Finance",
    employees: 2800,
    founded: 2009,
    revenue: "$425M",
    description: "Banking and financial technology solutions",
  },
  {
    id: 11,
    name: "AgriTech Solutions",
    location: "Des Moines, IA",
    industry: "Agriculture",
    employees: 540,
    founded: 2017,
    revenue: "$67M",
    description: "Smart farming and agricultural technology",
  },
  {
    id: 12,
    name: "MediaWorks Digital",
    location: "Los Angeles, CA",
    industry: "Media",
    employees: 1100,
    founded: 2013,
    revenue: "$156M",
    description: "Digital media production and streaming services",
  },
  {
    id: 13,
    name: "CyberSecure Pro",
    location: "Washington, DC",
    industry: "Technology",
    employees: 780,
    founded: 2015,
    revenue: "$112M",
    description: "Cybersecurity and threat intelligence solutions",
  },
  {
    id: 14,
    name: "BuildSmart Construction",
    location: "Houston, TX",
    industry: "Construction",
    employees: 3200,
    founded: 2006,
    revenue: "$520M",
    description: "Commercial construction and project management",
  },
  {
    id: 15,
    name: "FoodTech Ventures",
    location: "Portland, OR",
    industry: "Food & Beverage",
    employees: 890,
    founded: 2019,
    revenue: "$84M",
    description: "Food technology and sustainable packaging",
  },
  {
    id: 16,
    name: "TransLogistics Global",
    location: "Atlanta, GA",
    industry: "Logistics",
    employees: 4100,
    founded: 2007,
    revenue: "$675M",
    description: "Supply chain and logistics management",
  },
  {
    id: 17,
    name: "EduTech Academy",
    location: "Philadelphia, PA",
    industry: "Education",
    employees: 620,
    founded: 2016,
    revenue: "$72M",
    description: "Online learning platforms and educational technology",
  },
  {
    id: 18,
    name: "GameForge Studios",
    location: "San Francisco, CA",
    industry: "Entertainment",
    employees: 450,
    founded: 2018,
    revenue: "$58M",
    description: "Video game development and publishing",
  },
  {
    id: 19,
    name: "LegalTech Partners",
    location: "New York, NY",
    industry: "Legal",
    employees: 340,
    founded: 2020,
    revenue: "$45M",
    description: "Legal technology and case management software",
  },
  {
    id: 20,
    name: "AeroSpace Dynamics",
    location: "Denver, CO",
    industry: "Aerospace",
    employees: 2500,
    founded: 2010,
    revenue: "$389M",
    description: "Aerospace engineering and satellite systems",
  },
  {
    id: 21,
    name: "FashionForward Group",
    location: "Miami, FL",
    industry: "Retail",
    employees: 1900,
    founded: 2012,
    revenue: "$234M",
    description: "Fashion retail and e-commerce platform",
  },
  {
    id: 22,
    name: "InsureTech Solutions",
    location: "Hartford, CT",
    industry: "Finance",
    employees: 1560,
    founded: 2014,
    revenue: "$198M",
    description: "Insurance technology and risk management",
  },
  {
    id: 23,
    name: "SmartHome Systems",
    location: "Phoenix, AZ",
    industry: "Technology",
    employees: 820,
    founded: 2017,
    revenue: "$103M",
    description: "Home automation and IoT solutions",
  },
  {
    id: 24,
    name: "PharmaCare Corp",
    location: "Indianapolis, IN",
    industry: "Healthcare",
    employees: 2700,
    founded: 2008,
    revenue: "$412M",
    description: "Pharmaceutical distribution and healthcare services",
  },
  {
    id: 25,
    name: "SolarTech Innovations",
    location: "Las Vegas, NV",
    industry: "Energy",
    employees: 1340,
    founded: 2015,
    revenue: "$176M",
    description: "Solar energy systems and renewable technology",
  },
  {
    id: 26,
    name: "TravelHub Network",
    location: "Orlando, FL",
    industry: "Travel",
    employees: 980,
    founded: 2011,
    revenue: "$134M",
    description: "Travel booking and hospitality management",
  },
  {
    id: 27,
    name: "RoboTech Engineering",
    location: "Pittsburgh, PA",
    industry: "Technology",
    employees: 670,
    founded: 2019,
    revenue: "$87M",
    description: "Robotics and automation solutions",
  },
  {
    id: 28,
    name: "PetCare Plus",
    location: "Nashville, TN",
    industry: "Consumer Goods",
    employees: 540,
    founded: 2016,
    revenue: "$69M",
    description: "Pet care products and veterinary services",
  },
  {
    id: 29,
    name: "SportTech Innovations",
    location: "Dallas, TX",
    industry: "Sports",
    employees: 420,
    founded: 2018,
    revenue: "$54M",
    description: "Sports technology and performance analytics",
  },
  {
    id: 30,
    name: "ChemCore Industries",
    location: "Wilmington, DE",
    industry: "Manufacturing",
    employees: 3100,
    founded: 2005,
    revenue: "$498M",
    description: "Chemical manufacturing and industrial solutions",
  },
  {
    id: 31,
    name: "AquaPure Systems",
    location: "Milwaukee, WI",
    industry: "Environmental",
    employees: 760,
    founded: 2013,
    revenue: "$94M",
    description: "Water purification and environmental technology",
  },
  {
    id: 32,
    name: "MusicStream Pro",
    location: "Austin, TX",
    industry: "Entertainment",
    employees: 380,
    founded: 2020,
    revenue: "$42M",
    description: "Music streaming and artist management platform",
  },
  {
    id: 33,
    name: "PropTech Ventures",
    location: "San Francisco, CA",
    industry: "Real Estate",
    employees: 590,
    founded: 2017,
    revenue: "$76M",
    description: "Real estate technology and property management",
  },
  {
    id: 34,
    name: "BioFuel Energy",
    location: "Omaha, NE",
    industry: "Energy",
    employees: 910,
    founded: 2011,
    revenue: "$118M",
    description: "Biofuel production and renewable energy",
  },
  {
    id: 35,
    name: "TextileTech Corp",
    location: "Charlotte, NC",
    industry: "Manufacturing",
    employees: 1450,
    founded: 2009,
    revenue: "$187M",
    description: "Advanced textile manufacturing and materials",
  },
  {
    id: 36,
    name: "VirtualReality Labs",
    location: "Seattle, WA",
    industry: "Technology",
    employees: 520,
    founded: 2019,
    revenue: "$63M",
    description: "Virtual reality and augmented reality solutions",
  },
  {
    id: 37,
    name: "FarmFresh Organics",
    location: "Sacramento, CA",
    industry: "Agriculture",
    employees: 680,
    founded: 2014,
    revenue: "$89M",
    description: "Organic farming and sustainable food production",
  },
  {
    id: 38,
    name: "CryptoVault Securities",
    location: "New York, NY",
    industry: "Finance",
    employees: 290,
    founded: 2021,
    revenue: "$38M",
    description: "Cryptocurrency exchange and blockchain solutions",
  },
  {
    id: 39,
    name: "PrintMedia Solutions",
    location: "Minneapolis, MN",
    industry: "Media",
    employees: 840,
    founded: 2010,
    revenue: "$106M",
    description: "Digital printing and media production services",
  },
  {
    id: 40,
    name: "DroneDelivery Services",
    location: "San Diego, CA",
    industry: "Logistics",
    employees: 460,
    founded: 2018,
    revenue: "$57M",
    description: "Drone delivery and aerial logistics solutions",
  },
  {
    id: 41,
    name: "WellnessTech Group",
    location: "Boulder, CO",
    industry: "Healthcare",
    employees: 730,
    founded: 2016,
    revenue: "$92M",
    description: "Wellness apps and health monitoring technology",
  },
  {
    id: 42,
    name: "SteelWorks Manufacturing",
    location: "Cleveland, OH",
    industry: "Manufacturing",
    employees: 2300,
    founded: 2007,
    revenue: "$356M",
    description: "Steel production and metal fabrication",
  },
  {
    id: 43,
    name: "EventPro Management",
    location: "Las Vegas, NV",
    industry: "Entertainment",
    employees: 650,
    founded: 2015,
    revenue: "$81M",
    description: "Event management and conference planning",
  },
  {
    id: 44,
    name: "NanoTech Materials",
    location: "Cambridge, MA",
    industry: "Technology",
    employees: 380,
    founded: 2020,
    revenue: "$46M",
    description: "Nanotechnology and advanced materials research",
  },
  {
    id: 45,
    name: "OceanFreight Lines",
    location: "Seattle, WA",
    industry: "Logistics",
    employees: 1890,
    founded: 2009,
    revenue: "$289M",
    description: "International shipping and freight forwarding",
  },
  {
    id: 46,
    name: "BakeryTech Systems",
    location: "Portland, OR",
    industry: "Food & Beverage",
    employees: 420,
    founded: 2017,
    revenue: "$52M",
    description: "Commercial baking equipment and automation",
  },
  {
    id: 47,
    name: "QuantumCompute Inc.",
    location: "Palo Alto, CA",
    industry: "Technology",
    employees: 310,
    founded: 2021,
    revenue: "$39M",
    description: "Quantum computing research and development",
  },
  {
    id: 48,
    name: "GreenBuild Architects",
    location: "Portland, OR",
    industry: "Construction",
    employees: 560,
    founded: 2013,
    revenue: "$71M",
    description: "Sustainable architecture and green building design",
  },
  {
    id: 49,
    name: "PackagePro Logistics",
    location: "Memphis, TN",
    industry: "Logistics",
    employees: 2900,
    founded: 2006,
    revenue: "$445M",
    description: "Package delivery and warehouse management",
  },
  {
    id: 50,
    name: "AIAssist Technologies",
    location: "San Francisco, CA",
    industry: "Technology",
    employees: 890,
    founded: 2019,
    revenue: "$114M",
    description: "AI-powered business automation and assistants",
  },
  {
    id: 51,
    name: "CleanEnergy Solutions",
    location: "Denver, CO",
    industry: "Energy",
    employees: 1120,
    founded: 2014,
    revenue: "$147M",
    description: "Clean energy consulting and implementation",
  },
  {
    id: 52,
    name: "MobilePay Systems",
    location: "San Jose, CA",
    industry: "Finance",
    employees: 670,
    founded: 2016,
    revenue: "$86M",
    description: "Mobile payment solutions and digital wallets",
  },
  {
    id: 53,
    name: "LuxuryHotels Group",
    location: "Miami, FL",
    industry: "Travel",
    employees: 3500,
    founded: 2008,
    revenue: "$578M",
    description: "Luxury hotel chain and hospitality services",
  },
  {
    id: 54,
    name: "DataGuard Security",
    location: "Austin, TX",
    industry: "Technology",
    employees: 540,
    founded: 2018,
    revenue: "$68M",
    description: "Data security and privacy compliance solutions",
  },
  {
    id: 55,
    name: "VitaminPlus Health",
    location: "Los Angeles, CA",
    industry: "Healthcare",
    employees: 780,
    founded: 2012,
    revenue: "$99M",
    description: "Nutritional supplements and wellness products",
  },
  {
    id: 56,
    name: "AeroLogistics Express",
    location: "Louisville, KY",
    industry: "Logistics",
    employees: 2400,
    founded: 2010,
    revenue: "$367M",
    description: "Air freight and express delivery services",
  },
  {
    id: 57,
    name: "CraftBrew Distributors",
    location: "Portland, OR",
    industry: "Food & Beverage",
    employees: 320,
    founded: 2015,
    revenue: "$41M",
    description: "Craft beer distribution and brewery services",
  },
  {
    id: 58,
    name: "WearableTech Innovations",
    location: "San Francisco, CA",
    industry: "Technology",
    employees: 470,
    founded: 2019,
    revenue: "$59M",
    description: "Wearable technology and fitness devices",
  },
  {
    id: 59,
    name: "MarineShipping Corp",
    location: "Norfolk, VA",
    industry: "Logistics",
    employees: 1650,
    founded: 2009,
    revenue: "$254M",
    description: "Marine shipping and port logistics",
  },
  {
    id: 60,
    name: "3DPrint Solutions",
    location: "Detroit, MI",
    industry: "Manufacturing",
    employees: 590,
    founded: 2016,
    revenue: "$74M",
    description: "3D printing services and additive manufacturing",
  },
  {
    id: 61,
    name: "CloudStorage Plus",
    location: "Seattle, WA",
    industry: "Technology",
    employees: 720,
    founded: 2014,
    revenue: "$91M",
    description: "Cloud storage and data backup solutions",
  },
  {
    id: 62,
    name: "BioGenetics Research",
    location: "Boston, MA",
    industry: "Healthcare",
    employees: 950,
    founded: 2011,
    revenue: "$126M",
    description: "Genetic research and personalized medicine",
  },
  {
    id: 63,
    name: "ElectricVehicle Motors",
    location: "Fremont, CA",
    industry: "Automotive",
    employees: 2100,
    founded: 2013,
    revenue: "$321M",
    description: "Electric vehicle manufacturing and batteries",
  },
  {
    id: 64,
    name: "DigitalMarketing Hub",
    location: "New York, NY",
    industry: "Media",
    employees: 880,
    founded: 2015,
    revenue: "$109M",
    description: "Digital marketing and advertising services",
  },
  {
    id: 65,
    name: "SmartCity Systems",
    location: "Chicago, IL",
    industry: "Technology",
    employees: 1340,
    founded: 2017,
    revenue: "$172M",
    description: "Smart city infrastructure and IoT solutions",
  },
  {
    id: 66,
    name: "OrganicCosmetics Co",
    location: "Los Angeles, CA",
    industry: "Consumer Goods",
    employees: 620,
    founded: 2018,
    revenue: "$78M",
    description: "Organic beauty products and cosmetics",
  },
  {
    id: 67,
    name: "TelemedicineNow",
    location: "Phoenix, AZ",
    industry: "Healthcare",
    employees: 540,
    founded: 2020,
    revenue: "$66M",
    description: "Telemedicine platform and virtual consultations",
  },
  {
    id: 68,
    name: "InvestTech Partners",
    location: "New York, NY",
    industry: "Finance",
    employees: 980,
    founded: 2012,
    revenue: "$137M",
    description: "Investment management and robo-advisory",
  },
  {
    id: 69,
    name: "RecycleTech Solutions",
    location: "San Francisco, CA",
    industry: "Environmental",
    employees: 490,
    founded: 2016,
    revenue: "$62M",
    description: "Recycling technology and waste management",
  },
  {
    id: 70,
    name: "AviationTech Services",
    location: "Dallas, TX",
    industry: "Aerospace",
    employees: 1780,
    founded: 2010,
    revenue: "$273M",
    description: "Aviation maintenance and aerospace services",
  },
  {
    id: 71,
    name: "SmartRetail Systems",
    location: "Seattle, WA",
    industry: "Retail",
    employees: 1230,
    founded: 2014,
    revenue: "$159M",
    description: "Retail automation and point-of-sale systems",
  },
  {
    id: 72,
    name: "UrbanDevelopment Corp",
    location: "New York, NY",
    industry: "Real Estate",
    employees: 2500,
    founded: 2007,
    revenue: "$456M",
    description: "Urban real estate development and investment",
  },
  {
    id: 73,
    name: "TelecomNetwork Pro",
    location: "Atlanta, GA",
    industry: "Technology",
    employees: 3200,
    founded: 2009,
    revenue: "$512M",
    description: "Telecommunications infrastructure and services",
  },
  {
    id: 74,
    name: "CoffeeChain Ventures",
    location: "Seattle, WA",
    industry: "Food & Beverage",
    employees: 4800,
    founded: 2006,
    revenue: "$689M",
    description: "Coffee shop chain and beverage distribution",
  },
  {
    id: 75,
    name: "SoftwareDev Solutions",
    location: "Austin, TX",
    industry: "Technology",
    employees: 1560,
    founded: 2013,
    revenue: "$203M",
    description: "Custom software development and consulting",
  },
  {
    id: 76,
    name: "FutureFood Lab",
    location: "San Francisco, CA",
    industry: "Food & Beverage",
    employees: 410,
    founded: 2020,
    revenue: "$51M",
    description: "Plant-based protein and alternative food research",
  },
  {
    id: 77,
    name: "GlobalFinance Nexus",
    location: "New York, NY",
    industry: "Finance",
    employees: 4800,
    founded: 1998,
    revenue: "$1.2B",
    description: "Global investment banking and asset management",
  },
  {
    id: 78,
    name: "E-Learning Pro",
    location: "Boston, MA",
    industry: "Education",
    employees: 950,
    founded: 2017,
    revenue: "$115M",
    description: "AI-driven personalized education platforms",
  },
  {
    id: 79,
    name: "SolarPanel Dynamics",
    location: "Austin, TX",
    industry: "Energy",
    employees: 1900,
    founded: 2010,
    revenue: "$290M",
    description: "Manufacture and installation of commercial solar panels",
  },
  {
    id: 80,
    name: "HealthMetrics Corp",
    location: "Seattle, WA",
    industry: "Healthcare",
    employees: 1120,
    founded: 2016,
    revenue: "$142M",
    description: "Electronic health record systems and data analytics",
  },
  {
    id: 81,
    name: "FashionConnect Online",
    location: "Los Angeles, CA",
    industry: "Retail",
    employees: 1600,
    founded: 2011,
    revenue: "$260M",
    description: "High-end fashion e-commerce marketplace",
  },
  {
    id: 82,
    name: "RoadFreight Logistics",
    location: "Chicago, IL",
    industry: "Logistics",
    employees: 3800,
    founded: 2003,
    revenue: "$510M",
    description: "National truckload and less-than-truckload services",
  },
  {
    id: 83,
    name: "NextGen Robotics",
    location: "San Jose, CA",
    industry: "Technology",
    employees: 630,
    founded: 2018,
    revenue: "$79M",
    description: "Industrial automation and advanced robotics manufacturing",
  },
  {
    id: 84,
    name: "PharmaR&D Global",
    location: "San Diego, CA",
    industry: "Healthcare",
    employees: 2200,
    founded: 2005,
    revenue: "$550M",
    description: "Early-stage drug discovery and clinical trials",
  },
  {
    id: 85,
    name: "CryptoTrade Exchange",
    location: "New York, NY",
    industry: "Finance",
    employees: 710,
    founded: 2019,
    revenue: "$105M",
    description: "Regulated digital asset and cryptocurrency trading platform",
  },
  {
    id: 86,
    name: "AgriHarvest Tech",
    location: "Austin, TX",
    industry: "Agriculture",
    employees: 480,
    founded: 2015,
    revenue: "$61M",
    description: "Vertical farming solutions and indoor agriculture",
  },
  {
    id: 87,
    name: "FilmWorks Production",
    location: "Los Angeles, CA",
    industry: "Entertainment",
    employees: 1300,
    founded: 2008,
    revenue: "$220M",
    description: "Major motion picture and television content production",
  },
  {
    id: 88,
    name: "CyberDefense Shield",
    location: "Washington, DC",
    industry: "Technology",
    employees: 990,
    founded: 2014,
    revenue: "$135M",
    description: "Government and enterprise cybersecurity consulting",
  },
  {
    id: 89,
    name: "MetroBuild Engineering",
    location: "Houston, TX",
    industry: "Construction",
    employees: 4100,
    founded: 2001,
    revenue: "$750M",
    description: "Large-scale infrastructure and commercial building projects",
  },
  {
    id: 90,
    name: "Gourmet Meal Kits",
    location: "Portland, OR",
    industry: "Food & Beverage",
    employees: 600,
    founded: 2018,
    revenue: "$88M",
    description: "Subscription-based gourmet meal kit delivery service",
  },
  {
    id: 91,
    name: "GlobalAir Cargo",
    location: "Atlanta, GA",
    industry: "Logistics",
    employees: 2800,
    founded: 2005,
    revenue: "$410M",
    description: "International air freight and logistics solutions",
  },
  {
    id: 92,
    name: "STEM Educators Inc.",
    location: "Philadelphia, PA",
    industry: "Education",
    employees: 740,
    founded: 2015,
    revenue: "$90M",
    description: "K-12 STEM curriculum and teacher training",
  },
  {
    id: 93,
    name: "IndieGame Collective",
    location: "San Francisco, CA",
    industry: "Entertainment",
    employees: 350,
    founded: 2021,
    revenue: "$44M",
    description: "Publisher and incubator for independent video game studios",
  },
  {
    id: 94,
    name: "PatentPro Legal",
    location: "New York, NY",
    industry: "Legal",
    employees: 450,
    founded: 2007,
    revenue: "$65M",
    description: "Intellectual property law and patent litigation services",
  },
  {
    id: 95,
    name: "SpaceLaunch Ventures",
    location: "Denver, CO",
    industry: "Aerospace",
    employees: 1900,
    founded: 2012,
    revenue: "$310M",
    description: "Small satellite launch services and payload integration",
  },
  {
    id: 96,
    name: "HomeGoods Emporium",
    location: "Miami, FL",
    industry: "Retail",
    employees: 2500,
    founded: 2009,
    revenue: "$380M",
    description: "Online and physical stores for home decor and furnishings",
  },
  {
    id: 97,
    name: "MortgageTech Services",
    location: "Hartford, CT",
    industry: "Finance",
    employees: 1400,
    founded: 2015,
    revenue: "$175M",
    description: "Digital mortgage origination and servicing software",
  },
  {
    id: 98,
    name: "SmartEnergy Grid",
    location: "Phoenix, AZ",
    industry: "Technology",
    employees: 870,
    founded: 2016,
    revenue: "$110M",
    description: "Smart grid technology and energy distribution optimization",
  },
  {
    id: 99,
    name: "ElderCare Solutions",
    location: "Indianapolis, IN",
    industry: "Healthcare",
    employees: 3100,
    founded: 2004,
    revenue: "$480M",
    description: "Senior living management and home healthcare services",
  },
  {
    id: 100,
    name: "WindFarm Developers",
    location: "Las Vegas, NV",
    industry: "Energy",
    employees: 1500,
    founded: 2013,
    revenue: "$210M",
    description: "Onshore and offshore wind power project development",
  },
  {
    id: 101,
    name: "ResortGetaways Intl",
    location: "Orlando, FL",
    industry: "Travel",
    employees: 1200,
    founded: 2010,
    revenue: "$165M",
    description: "Luxury resort management and vacation packages",
  },
  {
    id: 102,
    name: "AI-Factory Automation",
    location: "Pittsburgh, PA",
    industry: "Manufacturing",
    employees: 780,
    founded: 2017,
    revenue: "$101M",
    description: "AI-powered quality control and factory automation systems",
  },
  {
    id: 103,
    name: "OrganicSnacks Co",
    location: "Nashville, TN",
    industry: "Consumer Goods",
    employees: 680,
    founded: 2015,
    revenue: "$85M",
    description: "Manufacturer and distributor of organic snack foods",
  },
  {
    id: 104,
    name: "E-Sports League Pro",
    location: "Dallas, TX",
    industry: "Entertainment",
    employees: 510,
    founded: 2019,
    revenue: "$70M",
    description: "Professional esports league organization and broadcasting",
  },
  {
    id: 105,
    name: "PolymerInnovations",
    location: "Wilmington, DE",
    industry: "Manufacturing",
    employees: 3500,
    founded: 2003,
    revenue: "$550M",
    description: "Specialty chemical and advanced polymer production",
  },
  {
    id: 106,
    name: "WaterCycle Management",
    location: "Milwaukee, WI",
    industry: "Environmental",
    employees: 890,
    founded: 2015,
    revenue: "$110M",
    description: "Industrial wastewater treatment and conservation solutions",
  },
  {
    id: 107,
    name: "Podcast Media Group",
    location: "Austin, TX",
    industry: "Media",
    employees: 420,
    founded: 2018,
    revenue: "$56M",
    description: "Premium podcast production and advertising network",
  },
  {
    id: 108,
    name: "CommercialRealty Fund",
    location: "San Francisco, CA",
    industry: "Real Estate",
    employees: 700,
    founded: 2014,
    revenue: "$108M",
    description: "Acquisition and management of commercial office properties",
  },
  {
    id: 109,
    name: "Geothermal Power Co.",
    location: "Denver, CO",
    industry: "Energy",
    employees: 1250,
    founded: 2016,
    revenue: "$155M",
    description: "Geothermal energy plant construction and operation",
  },
  {
    id: 110,
    name: "AutoParts Robotics",
    location: "Detroit, MI",
    industry: "Automotive",
    employees: 1850,
    founded: 2010,
    revenue: "$280M",
    description: "Manufacturing of specialized robotic components for vehicles",
  },
  {
    id: 111,
    name: "AR/VR Training",
    location: "Seattle, WA",
    industry: "Technology",
    employees: 550,
    founded: 2020,
    revenue: "$71M",
    description:
      "Augmented and virtual reality solutions for corporate training",
  },
  {
    id: 112,
    name: "Sustainable Harvests",
    location: "Sacramento, CA",
    industry: "Agriculture",
    employees: 790,
    founded: 2012,
    revenue: "$105M",
    description: "Large-scale sustainable farming and distribution",
  },
  {
    id: 113,
    name: "DigitalBank USA",
    location: "New York, NY",
    industry: "Finance",
    employees: 3100,
    founded: 2005,
    revenue: "$520M",
    description: "Fully digital bank with consumer and business accounts",
  },
  {
    id: 114,
    name: "LocalNews Network",
    location: "Minneapolis, MN",
    industry: "Media",
    employees: 910,
    founded: 2008,
    revenue: "$125M",
    description:
      "Regional news organization with digital and broadcast presence",
  },
  {
    id: 115,
    name: "ColdChain Express",
    location: "Memphis, TN",
    industry: "Logistics",
    employees: 2600,
    founded: 2011,
    revenue: "$390M",
    description:
      "Temperature-controlled logistics for pharmaceuticals and food",
  },
  {
    id: 116,
    name: "MentalHealth Connect",
    location: "Boulder, CO",
    industry: "Healthcare",
    employees: 600,
    founded: 2017,
    revenue: "$75M",
    description: "Teletherapy and mental wellness digital services",
  },
  {
    id: 117,
    name: "Precision Metals",
    location: "Cleveland, OH",
    industry: "Manufacturing",
    employees: 2800,
    founded: 1995,
    revenue: "$450M",
    description:
      "High-precision metal components for aerospace and medical devices",
  },
  {
    id: 118,
    name: "LiveEvent Ticketing",
    location: "Las Vegas, NV",
    industry: "Entertainment",
    employees: 720,
    founded: 2016,
    revenue: "$98M",
    description: "Platform for ticket sales and management for large events",
  },
  {
    id: 119,
    name: "BioNano Tech",
    location: "Cambridge, MA",
    industry: "Technology",
    employees: 400,
    founded: 2021,
    revenue: "$48M",
    description: "Research into biological applications of nanotechnology",
  },
  {
    id: 120,
    name: "PortLogistics Pro",
    location: "Norfolk, VA",
    industry: "Logistics",
    employees: 2100,
    founded: 2004,
    revenue: "$320M",
    description: "Automated port operations and container handling",
  },
  {
    id: 121,
    name: "Brewery Automation",
    location: "Portland, OR",
    industry: "Food & Beverage",
    employees: 510,
    founded: 2018,
    revenue: "$64M",
    description: "Specialized equipment and automation for craft breweries",
  },
  {
    id: 122,
    name: "DeepLearning Labs",
    location: "Palo Alto, CA",
    industry: "Technology",
    employees: 350,
    founded: 2022,
    revenue: "$41M",
    description: "Advanced deep learning models and custom AI development",
  },
  {
    id: 123,
    name: "ModularHome Builders",
    location: "Portland, OR",
    industry: "Construction",
    employees: 750,
    founded: 2016,
    revenue: "$95M",
    description:
      "Sustainable, prefabricated modular homes and commercial units",
  },
  {
    id: 124,
    name: "QuickPackage Delivery",
    location: "Memphis, TN",
    industry: "Logistics",
    employees: 3100,
    founded: 2007,
    revenue: "$480M",
    description: "Regional same-day and next-day package delivery services",
  },
  {
    id: 125,
    name: "AI-Powered HR",
    location: "San Francisco, CA",
    industry: "Technology",
    employees: 950,
    founded: 2020,
    revenue: "$125M",
    description: "AI software for recruiting, onboarding, and HR management",
  },
  {
    id: 126,
    name: "CarbonCapture Solutions",
    location: "Denver, CO",
    industry: "Environmental",
    employees: 1050,
    founded: 2015,
    revenue: "$130M",
    description: "Industrial carbon capture and storage technologies",
  },
  {
    id: 127,
    name: "P2P Lending Network",
    location: "San Jose, CA",
    industry: "Finance",
    employees: 780,
    founded: 2017,
    revenue: "$95M",
    description:
      "Peer-to-peer lending platform for personal and small business loans",
  },
  {
    id: 128,
    name: "Boutique Stays Group",
    location: "Miami, FL",
    industry: "Travel",
    employees: 4000,
    founded: 2010,
    revenue: "$610M",
    description: "Chain of high-end boutique hotels and travel experiences",
  },
  {
    id: 129,
    name: "EdgeCompute Systems",
    location: "Austin, TX",
    industry: "Technology",
    employees: 610,
    founded: 2019,
    revenue: "$78M",
    description: "Hardware and software for distributed edge computing",
  },
  {
    id: 130,
    name: "TeleHealth Kids",
    location: "Los Angeles, CA",
    industry: "Healthcare",
    employees: 840,
    founded: 2014,
    revenue: "$115M",
    description: "Pediatric-focused telemedicine and remote monitoring",
  },
  {
    id: 131,
    name: "FreightTrain Rail",
    location: "Chicago, IL",
    industry: "Logistics",
    employees: 3300,
    founded: 2001,
    revenue: "$540M",
    description: "Intermodal and rail freight shipping services",
  },
  {
    id: 132,
    name: "Artisan Coffee Roasters",
    location: "Portland, OR",
    industry: "Food & Beverage",
    employees: 380,
    founded: 2016,
    revenue: "$49M",
    description: "Specialty coffee roasting and wholesale distribution",
  },
  {
    id: 133,
    name: "Wearable Diagnostics",
    location: "San Francisco, CA",
    industry: "Technology",
    employees: 530,
    founded: 2020,
    revenue: "$68M",
    description: "Wearable devices for continuous medical diagnostics",
  },
  {
    id: 134,
    name: "Shipyard Builders",
    location: "Norfolk, VA",
    industry: "Manufacturing",
    employees: 4500,
    founded: 1985,
    revenue: "$790M",
    description: "Commercial and naval shipbuilding and repair",
  },
  {
    id: 135,
    name: "AutoLeasing Solutions",
    location: "Fremont, CA",
    industry: "Finance",
    employees: 1100,
    founded: 2014,
    revenue: "$145M",
    description: "Online platform for vehicle leasing and fleet management",
  },
  {
    id: 136,
    name: "Creative Content Studio",
    location: "New York, NY",
    industry: "Media",
    employees: 920,
    founded: 2016,
    revenue: "$118M",
    description: "Branded content production and digital media strategy",
  },
  {
    id: 137,
    name: "SmartUtility Meters",
    location: "Chicago, IL",
    industry: "Technology",
    employees: 1500,
    founded: 2018,
    revenue: "$190M",
    description:
      "Manufacturing of smart utility metering and sensor technology",
  },
  {
    id: 138,
    name: "Ethical Grooming Co",
    location: "Los Angeles, CA",
    industry: "Consumer Goods",
    employees: 710,
    founded: 2019,
    revenue: "$92M",
    description: "Sustainable and ethically sourced personal grooming products",
  },
  {
    id: 139,
    name: "RemotePatient Monitoring",
    location: "Phoenix, AZ",
    industry: "Healthcare",
    employees: 620,
    founded: 2021,
    revenue: "$79M",
    description: "Hardware and software for remote patient health monitoring",
  },
  {
    id: 140,
    name: "WealthManagement AI",
    location: "New York, NY",
    industry: "Finance",
    employees: 1150,
    founded: 2013,
    revenue: "$155M",
    description: "AI-driven portfolio management and wealth advisory services",
  },
  {
    id: 141,
    name: "Eco-Waste Management",
    location: "San Francisco, CA",
    industry: "Environmental",
    employees: 550,
    founded: 2017,
    revenue: "$71M",
    description: "Commercial composting and organic waste diversion",
  },
  {
    id: 142,
    name: "Defense Systems Tech",
    location: "Dallas, TX",
    industry: "Aerospace",
    employees: 2300,
    founded: 2006,
    revenue: "$340M",
    description: "Development of defense and security aerospace technologies",
  },
  {
    id: 143,
    name: "PopUp Retail Solutions",
    location: "Seattle, WA",
    industry: "Retail",
    employees: 1400,
    founded: 2015,
    revenue: "$180M",
    description:
      "Temporary and flexible retail space management and technology",
  },
  {
    id: 144,
    name: "Luxury Condos Inc.",
    location: "New York, NY",
    industry: "Real Estate",
    employees: 2800,
    founded: 2004,
    revenue: "$510M",
    description: "Development and sales of high-end residential real estate",
  },
  {
    id: 145,
    name: "FiberOptic Networks",
    location: "Atlanta, GA",
    industry: "Technology",
    employees: 3500,
    founded: 2008,
    revenue: "$590M",
    description:
      "Installation and management of high-speed fiber optic networks",
  },
  {
    id: 146,
    name: "Restaurant POS Systems",
    location: "Austin, TX",
    industry: "Food & Beverage",
    employees: 1700,
    founded: 2014,
    revenue: "$220M",
    description: "Cloud-based point-of-sale and restaurant management software",
  },
  {
    id: 147,
    name: "EdTech Gamification",
    location: "San Jose, CA",
    industry: "Education",
    employees: 640,
    founded: 2019,
    revenue: "$82M",
    description: "Educational software utilizing gamification for learning",
  },
  {
    id: 148,
    name: "Sports Data Analytics",
    location: "Dallas, TX",
    industry: "Sports",
    employees: 480,
    founded: 2017,
    revenue: "$60M",
    description: "Advanced data analytics for professional sports teams",
  },
  {
    id: 149,
    name: "Custom Manufacturing",
    location: "Houston, TX",
    industry: "Manufacturing",
    employees: 3800,
    founded: 2000,
    revenue: "$620M",
    description: "Contract manufacturing for complex industrial components",
  },
  {
    id: 150,
    name: "CoastalTravel Agency",
    location: "Miami, FL",
    industry: "Travel",
    employees: 1100,
    founded: 2015,
    revenue: "$150M",
    description: "Specialized travel agency for coastal and cruise vacations",
  },
];

export const industries = [
  "All",
  "Technology",
  "Finance",
  "Healthcare",
  "Energy",
  "Retail",
  "Automotive",
  "Media",
  "Construction",
  "Food & Beverage",
  "Logistics",
  "Education",
  "Entertainment",
  "Legal",
  "Aerospace",
  "Travel",
  "Consumer Goods",
  "Sports",
  "Manufacturing",
  "Environmental",
  "Real Estate",
  "Agriculture"
];

export const locations = [
  "All",
  "San Francisco, CA",
  "New York, NY",
  "Boston, MA",
  "Austin, TX",
  "Seattle, WA",
  "Chicago, IL",
  "Detroit, MI",
  "San Jose, CA",
  "San Diego, CA",
  "Los Angeles, CA",
  "Denver, CO",
  "Miami, FL",
  "Portland, OR",
  "Phoenix, AZ",
  "Dallas, TX",
  "Atlanta, GA"
];
